exports.recipes = [
    {SKUNumber: 'BM884752', SKUName: 'blueberry muffin', status: 'finished product', yields: 8, ingredients: [ {ingredientQuantity: 200, ingredientUnit: 'grams', ingredientName: 'all-purpose flour'}, {ingredientQuantity: 100, ingredientUnit: 'grams', ingredientName: 'white sugar'}, {ingredientQuantity: 20, ingredientUnit: 'grams', ingredientName: 'baking powder'}, {ingredientQuantity: 100, ingredientUnit: 'grams', ingredientName: 'butter'}, {ingredientQuantity: 1, ingredientUnit: 'pieces', ingredientName: 'large egg'}, {ingredientQuantity: 100, ingredientUnit: 'millilitres', ingredientName: 'milk'}, {ingredientQuantity: 200, ingredientUnit: 'grams', ingredientName: 'blueberries'} ] },
    
    {SKUNumber: 'BB884984', SKUName: 'banana bread', status: 'finished product', yields: 8, ingredients: [ {ingredientQuantity: 250, ingredientUnit: 'grams', ingredientName: 'all-purpose flour'}, {ingredientQuantity: 150, ingredientUnit: 'grams', ingredientName: 'brown sugar'}, {ingredientQuantity: 10, ingredientUnit: 'grams', ingredientName: 'baking soda'}, {ingredientQuantity: 100, ingredientUnit: 'grams', ingredientName: 'butter'}, {ingredientQuantity: 2, ingredientUnit: 'pieces', ingredientName: 'large egg'}, {ingredientQuantity: 2, ingredientUnit: 'pieces', ingredientName: 'banana'} ] },
    
    {SKUNumber: 'CC124236', SKUName: 'carrot cake muffins', status: 'finished product', yields: 12, ingredients: [ {ingredientQuantity: 150, ingredientUnit: 'grams', ingredientName: 'all-purpose flour'}, {ingredientQuantity: 125, ingredientUnit: 'grams', ingredientName: 'brown sugar'}, {ingredientQuantity: 10, ingredientUnit: 'grams', ingredientName: 'baking soda'}, {ingredientQuantity: 80, ingredientUnit: 'millilitres', ingredientName: 'vegetable oil'}, {ingredientQuantity: 2, ingredientUnit: 'pieces', ingredientName: 'large egg'}, {ingredientQuantity: 100, ingredientUnit: 'millilitres', ingredientName: 'milk'}, {ingredientQuantity: 200, ingredientUnit: 'grams', ingredientName: 'carrot'}, {ingredientQuantity: 75, ingredientUnit: 'grams', ingredientName: 'walnuts'} ] },

    {SKUNumber: 'HC113589', SKUName: 'ham and cheese toastie', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 80, ingredientUnit: 'grams', ingredientName: 'white bread'}, {ingredientQuantity: 40, ingredientUnit: 'grams', ingredientName: 'cheddar cheese'}, {ingredientQuantity: 40, ingredientUnit: 'grams', ingredientName: 'honey ham'}, {ingredientQuantity: 20, ingredientUnit: 'grams', ingredientName: 'butter'} ] },

    {SKUNumber: 'CS113711', SKUName: 'chicken schnitzel toastie', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 80, ingredientUnit: 'grams', ingredientName: 'multigrain bread'}, {ingredientQuantity: 100, ingredientUnit: 'grams', ingredientName: 'chicken schnitzel'}, {ingredientQuantity: 40, ingredientUnit: 'grams', ingredientName: 'colby cheese'}, {ingredientQuantity: 20, ingredientUnit: 'grams', ingredientName: 'butter'}, {ingredientQuantity: 35, ingredientUnit: 'grams', ingredientName: 'wombok'} ] },

    {SKUNumber: 'SC113912', SKUName: 'salmon and cheese toastie', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 80, ingredientUnit: 'grams', ingredientName: 'multigrain bread'}, {ingredientQuantity: 100, ingredientUnit: 'grams', ingredientName: 'salmon'}, {ingredientQuantity: 40, ingredientUnit: 'grams', ingredientName: 'cheddar cheese'}, {ingredientQuantity: 20, ingredientUnit: 'grams', ingredientName: 'mayonnaise'}, {ingredientQuantity: 20, ingredientUnit: 'grams', ingredientName: 'spinach'} ] },

    {SKUNumber: 'PC222416', SKUName: 'pancakes', status: 'finished product', yields: 4, ingredients: [ {ingredientQuantity: 300, ingredientUnit: 'grams', ingredientName: 'all-purpose flour'}, {ingredientQuantity: 40, ingredientUnit: 'grams', ingredientName: 'baking powder'}, {ingredientQuantity: 50, ingredientUnit: 'grams', ingredientName: 'white sugar'}, {ingredientQuantity: 1, ingredientUnit: 'pieces', ingredientName: 'large egg'}, {ingredientQuantity: 450, ingredientUnit: 'millilitres', ingredientName: 'milk'}, {ingredientQuantity: 150, ingredientUnit: 'grams', ingredientName: 'mixed berries'}, {ingredientQuantity: 50, ingredientUnit: 'millilitres', ingredientName: 'cream'} ] },

    {SKUNumber: 'WA332285', SKUName: 'waffles', status: 'finished product', yields: 5, ingredients: [ {ingredientQuantity: 300, ingredientUnit: 'grams', ingredientName: 'all-purpose flour'}, {ingredientQuantity: 40, ingredientUnit: 'grams', ingredientName: 'caster sugar'}, {ingredientQuantity: 4, ingredientUnit: 'pieces', ingredientName: 'large egg'}, {ingredientQuantity: 250, ingredientUnit: 'millilitres', ingredientName: 'milk'}, {ingredientQuantity: 150, ingredientUnit: 'grams', ingredientName: 'mixed berries'}, {ingredientQuantity: 50, ingredientUnit: 'millilitres', ingredientName: 'cream'} ] },

    {SKUNumber: 'ET115384', SKUName: 'eggs on toast', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 100, ingredientUnit: 'grams', ingredientName: 'sourdough bread'}, {ingredientQuantity: 3, ingredientUnit: 'pieces', ingredientName: 'large egg'}, {ingredientQuantity: 20, ingredientUnit: 'grams', ingredientName: 'cream'}, {ingredientQuantity: 15, ingredientUnit: 'grams', ingredientName: 'butter'} ] },

    {SKUNumber: 'AF115724', SKUName: 'avocado feta toast', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 100, ingredientUnit: 'grams', ingredientName: 'sourdough bread'}, {ingredientQuantity: 75, ingredientUnit: 'grams', ingredientName: 'avocado'}, {ingredientQuantity: 40, ingredientUnit: 'grams', ingredientName: 'feta cheese'}, {ingredientQuantity: 50, ingredientUnit: 'grams', ingredientName: 'cherry tomatoes'} ] },

    {SKUNumber: 'EC115005', SKUName: 'eggs, chorizo, white beans', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 60, ingredientUnit: 'grams', ingredientName: 'baguette'}, {ingredientQuantity: 125, ingredientUnit: 'grams', ingredientName: 'ricotta'}, {ingredientQuantity: 20, ingredientUnit: 'grams', ingredientName: 'chorizo'}, {ingredientQuantity: 200, ingredientUnit: 'grams', ingredientName: 'white beans'}, {ingredientQuantity: 2, ingredientUnit: 'pieces', ingredientName: 'large egg'}, {ingredientQuantity: 20, ingredientUnit: 'grams', ingredientName: 'butter'} ] },

    {SKUNumber: 'FW661681', SKUName: 'flat white', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 20, ingredientUnit: 'grams', ingredientName: 'coffee'}, {ingredientQuantity: 120, ingredientUnit: 'millilitres', ingredientName: 'milk'} ] },

    {SKUNumber: 'FW661681', SKUName: 'long black', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 20, ingredientUnit: 'grams', ingredientName: 'coffee'} ] },

    {SKUNumber: 'EB661407', SKUName: 'english breakfast tea', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 1, ingredientUnit: 'pieces', ingredientName: 'english breakfast tea bag'}, {ingredientQuantity: 15, ingredientUnit: 'millilitres', ingredientName: 'milk'} ] },

    {SKUNumber: 'EB661407', SKUName: 'banana smoothie', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 1, ingredientUnit: 'pieces', ingredientName: 'banana'}, {ingredientQuantity: 125, ingredientUnit: 'millilitres', ingredientName: 'milk'}, {ingredientQuantity: 125, ingredientUnit: 'grams', ingredientName: 'greek yogurt'} ] },

    {SKUNumber: 'MS770266', SKUName: 'mango smoothie', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 1, ingredientUnit: 'pieces', ingredientName: 'mango'}, {ingredientQuantity: 125, ingredientUnit: 'millilitres', ingredientName: 'milk'}, {ingredientQuantity: 125, ingredientUnit: 'grams', ingredientName: 'greek yogurt'} ] },

    {SKUNumber: 'BS770137', SKUName: 'berry smoothie', status: 'finished product', yields: 1, ingredients: [ {ingredientQuantity: 200, ingredientUnit: 'grams', ingredientName: 'mixed berries'}, {ingredientQuantity: 1, ingredientUnit: 'pieces', ingredientName: 'banana'}, {ingredientQuantity: 150, ingredientUnit: 'millilitres', ingredientName: 'milk'}, {ingredientQuantity: 50, ingredientUnit: 'grams', ingredientName: 'greek yogurt'} ] }
]